// Transaction-codec fixtures. Every hex was DECODED BY THE NODE
// (neuraid regtest, DePIN branch, v1.0.6.0-52297c1) and `txid`, `hash`,
// `size` and `vsize` are the values decoderawtransaction/getrawtransaction
// returned — never values computed by the codec under test, so txid/wtxid and
// the vout → vrefin → witness → locktime layout are validated against the
// node, not circularly.
//
// `walletV2` was fully generated by the node wallet (sendtoaddress +
// getrawtransaction). The other variants alter that base transaction
// (witness stacks, version 3, vrefin) and were then fed to the node's
// decoderawtransaction, which accepted them and produced the recorded values.

export interface TxCodecFixture {
  name: string;
  hex: string;
  txid: string;
  /** wtxid as the node reports it (`hash` field); equals txid without witness. */
  hash: string;
  version: number;
  vinCount: number;
  voutCount: number;
  size: number;
  vsize: number;
}

export const TX_CODEC_FIXTURES: TxCodecFixture[] = [
  {
    name: 'walletV2 (node-wallet signed, no witness)',
    hex: '0200000001d2935d6c8e84de047d7016feef1768faff0c775a2b1cbea9a3652a37c5174ca50000000049483045022100f251a09ed6ee3f99fb53df89c6bb8cf704a0c112fd5a9ab8ad0d2cd3e16d7165022063fe562a964d5d12722aaeae63a783ac0ac1f5711ac366d18ef83d067e61470001feffffff0240859beb8b0400001976a914ae7e837c212a37bb85dcaab8d85c3baf8666301c88ac00ca9a3b000000001976a914e88b2de2e8d16c1e1eb0b2e881ea6f3eab4d59a988ac6e000000',
    txid: '7dff637d422c6d9cc79dcb103b4da129e72cd00f474932a52b7ea75c41e7ea43',
    hash: '7dff637d422c6d9cc79dcb103b4da129e72cd00f474932a52b7ea75c41e7ea43',
    version: 2,
    vinCount: 1,
    voutCount: 2,
    size: 192,
    vsize: 192
  },
  {
    name: 'witnessV2 (marker/flags, mixed witness stacks)',
    hex: '02000000000102d2935d6c8e84de047d7016feef1768faff0c775a2b1cbea9a3652a37c5174ca50000000049483045022100f251a09ed6ee3f99fb53df89c6bb8cf704a0c112fd5a9ab8ad0d2cd3e16d7165022063fe562a964d5d12722aaeae63a783ac0ac1f5711ac366d18ef83d067e61470001feffffff22222222222222222222222222222222222222222222222222222222222222220100000000feffffff0240859beb8b0400001976a914ae7e837c212a37bb85dcaab8d85c3baf8666301c88ac00ca9a3b000000001976a914e88b2de2e8d16c1e1eb0b2e881ea6f3eab4d59a988ac0204aabbccdd00006e000000',
    txid: '36159f604da0a36252e8ce06e1903ad80e371741302a85d12ab01cdc2e18f98d',
    hash: 'f3c82d9faa148c56cc48565c782394201dd99c4437c5614b4b65187be4c9f86c',
    version: 2,
    vinCount: 2,
    voutCount: 2,
    size: 243,
    vsize: 236
  },
  {
    name: 'v3EmptyVrefin (version 3, vrefin = [])',
    hex: '0300000001d2935d6c8e84de047d7016feef1768faff0c775a2b1cbea9a3652a37c5174ca50000000049483045022100f251a09ed6ee3f99fb53df89c6bb8cf704a0c112fd5a9ab8ad0d2cd3e16d7165022063fe562a964d5d12722aaeae63a783ac0ac1f5711ac366d18ef83d067e61470001feffffff0240859beb8b0400001976a914ae7e837c212a37bb85dcaab8d85c3baf8666301c88ac00ca9a3b000000001976a914e88b2de2e8d16c1e1eb0b2e881ea6f3eab4d59a988ac006e000000',
    txid: '195e818953b6afb43b8bbdde5c89356b1a0630c01c27a554014122448132ae03',
    hash: '195e818953b6afb43b8bbdde5c89356b1a0630c01c27a554014122448132ae03',
    version: 3,
    vinCount: 1,
    voutCount: 2,
    size: 193,
    vsize: 193
  },
  {
    name: 'v3TwoVrefin (version 3, two refinputs)',
    hex: '0300000001d2935d6c8e84de047d7016feef1768faff0c775a2b1cbea9a3652a37c5174ca50000000049483045022100f251a09ed6ee3f99fb53df89c6bb8cf704a0c112fd5a9ab8ad0d2cd3e16d7165022063fe562a964d5d12722aaeae63a783ac0ac1f5711ac366d18ef83d067e61470001feffffff0240859beb8b0400001976a914ae7e837c212a37bb85dcaab8d85c3baf8666301c88ac00ca9a3b000000001976a914e88b2de2e8d16c1e1eb0b2e881ea6f3eab4d59a988ac02abababababababababababababababababababababababababababababababab07000000cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd000000006e000000',
    txid: '2b37358e4a5a87535d0a2c99ab29d373e46669b001e9397b11f72ae05c352731',
    hash: '2b37358e4a5a87535d0a2c99ab29d373e46669b001e9397b11f72ae05c352731',
    version: 3,
    vinCount: 1,
    voutCount: 2,
    size: 265,
    vsize: 265
  },
  {
    name: 'v3VrefinWitness (version 3, refinput + witness)',
    hex: '03000000000102d2935d6c8e84de047d7016feef1768faff0c775a2b1cbea9a3652a37c5174ca50000000049483045022100f251a09ed6ee3f99fb53df89c6bb8cf704a0c112fd5a9ab8ad0d2cd3e16d7165022063fe562a964d5d12722aaeae63a783ac0ac1f5711ac366d18ef83d067e61470001feffffff22222222222222222222222222222222222222222222222222222222222222220100000000feffffff0240859beb8b0400001976a914ae7e837c212a37bb85dcaab8d85c3baf8666301c88ac00ca9a3b000000001976a914e88b2de2e8d16c1e1eb0b2e881ea6f3eab4d59a988ac01efefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefef020000000204aabbccdd00006e000000',
    txid: 'ce3f0f4414452ed81d3a4aeda7861cfe4055fa30573ac6ef0aac531ccec53f31',
    hash: '73a5020f5a73d39b412c4c38dc7a8404015a25ea749c463b3bb011b0a91aeafb',
    version: 3,
    vinCount: 2,
    voutCount: 2,
    size: 280,
    vsize: 273
  }
];
